DROP DATABASE IF EXISTS BMI_PROJEKT;

CREATE DATABASE IF NOT EXISTS BMI_PROJEKT
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_hungarian_ci;

USE BMI_PROJEKT;

CREATE TABLE IF NOT EXISTS `kartya`(
    `UID` VARCHAR(255) NOT NULL,
    `kartyaTipus` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`UID`)
);

CREATE TABLE IF NOT EXISTS `szemelyek`(
    `OM` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `nev` VARCHAR(255) NOT NULL,
    `lakcim` VARCHAR(255) NOT NULL,
    `TAJ` CHAR(9) NOT NULL, 
    `nem` VARCHAR(255) NOT NULL,
    `szuletesiDatum` DATETIME NOT NULL,
    `osztaly` BIGINT NOT NULL,
    `kartya` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `meresek`(
    `id` BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `szemely` BIGINT NOT NULL,
    `testzsir%` BIGINT NOT NULL,
    `magassag` BIGINT NOT NULL,
    `suly` BIGINT NOT NULL,
    `datum` DATETIME NOT NULL
);

ALTER TABLE
    `szemelyek` ADD CONSTRAINT `szemelyek_kartya_foreign` FOREIGN KEY(`kartya`) REFERENCES `kartya`(`UID`);

ALTER TABLE
    `meresek` ADD CONSTRAINT `meresek_szemely_foreign` FOREIGN KEY(`szemely`) REFERENCES `szemelyek`(`OM`);